version: '3.7'
services:
  redis-cart:
    image: redis:alpine
    networks:
      - online-boutique
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  adservice:
    image: microservices-demo/adservice
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - PORT=9555
      - OTEL_RESOURCE_ATTRIBUTES=service.name=adservice
    ports:
      - "9555:9555"
  cartservice:
    image: microservices-demo/cartservice
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=cartservice
      - REDIS_ADDR=redis-cart:6379
    ports:
      - "7070:7070"
  checkoutservice:
    image: microservices-demo/checkoutservice
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - PORT=5050
      - OTEL_RESOURCE_ATTRIBUTES=service.name=checkoutservice
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50069
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:9090
      - CURRENCY_SERVICE_ADDR=currencyservice:6969
      - CART_SERVICE_ADDR=cartservice:7070
    ports:
      - "5050:5050"
  currencyservice:
    image: microservices-demo/currencyservice
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - PORT=6969
      - OTEL_RESOURCE_ATTRIBUTES=service.name=currencyservice
    ports:
      - "6969:6969"
  emailservice:
    image: microservices-demo/emailservice
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - PORT=9090
      - OTEL_RESOURCE_ATTRIBUTES=service.name=emailservice
    ports:
      - "9090:9090"
  frontend:
    image: microservices-demo/frontend
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - PORT=8090
      - OTEL_RESOURCE_ATTRIBUTES=service.name=frontend
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50069
      - CURRENCY_SERVICE_ADDR=currencyservice:6969
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8089
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
    ports:
      - "8090:8090"
  paymentservice:
    image: microservices-demo/paymentservice
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - PORT=50051
      - OTEL_RESOURCE_ATTRIBUTES=service.name=paymentservice
    ports:
      - "50051:50051"
  productcatalogservice:
    image: microservices-demo/productcatalogservice
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - PORT=3550
      - OTEL_RESOURCE_ATTRIBUTES=service.name=productcatalogservice
    ports:
      - "3550:3550"
  recommendationservice:
    image: microservices-demo/recommendationservice
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - PORT=8089
      - OTEL_RESOURCE_ATTRIBUTES=service.name=recommendationservice
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
    ports:
      - "8089:8089"
  shippingservice:
    image: microservices-demo/shippingservice
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - PORT=50069
      - OTEL_RESOURCE_ATTRIBUTES=service.name=shippingservice
    ports:
      - "50069:50069"
  loadgenerator:
    image: microservices-demo/loadgenerator
    networks:
      - online-boutique
    env_file:
      - .common.env
    extra_hosts:
      - signoz:host-gateway
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=loadgenerator
      - FRONTEND_ADDR=frontend:8090
      - USERS=10

volumes:
  redis-data:
networks:
  online-boutique:
