apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcollector
spec:
  selector:
    matchLabels:
      app: otelcollector
  template:
    metadata:
      labels:
        app: otelcollector
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: otelcollector
        image: otelcollector
        ports:
        - containerPort: 1888
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 13133
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 55670
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: otelcollector
spec:
  type: ClusterIP
  selector:
    app: otelcollector
  ports:
  - name: pprof
    port: 1888
    targetPort: 1888
  - name: collectormetrics
    port: 8888
    targetPort: 8888
  - name: prom
    port: 8889
    targetPort: 8889
  - name: healthcheck
    port: 13133
    targetPort: 13133
  - name: otlpgrpc
    port: 4317
    targetPort: 4317
  - name: otlphttp
    port: 4318
    targetPort: 4318
  - name: zpages
    port: 55670
    targetPort: 55670
